function:
  sample:
    handler: sample_lambda.sample.sample
    name: ${opt:stage, '${env:USERNAME}'}-${self:service}-sample
    role: sampleRole
    layers:
      - ${ssm:/${self:custom.app-name}/${opt:stage, ssm:/${env:USERNAME}'}/lambda/layer/utils, '/${self:custom.app-name}/dev/lambda/layer/utils}
    package:
      include:
        - sample_lambda/**
      exclude:
        - sample_lambda/sample.yml
    events:
      - http:
          path: ${self:custom.plugin-name}/sample
          method: get
          authorizer: ${self:custom.apiGatewayConfig.authorizer}

role:
  sampleRole:
    Type: AWS::IAM::Role
    Properties:
      Path:
        # Not allowed '-' characters in a path
        Fn::Join:
          - ""
          - Fn::Split:
              - "-"
              - /${self:custom.app-name}/${opt:stage, '${env:USERNAME}'}/${self:service}/sample/
      RoleName: ${opt:stage, '${env:USERNAME}'}-${self:service}-sample
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole