FROM alpine:latest

# Install nmap
RUN apk --update --no-cache add nmap nmap-scripts python3
RUN pip3 install awscli --upgrade

COPY task_script.sh .

ENV HOST_TO_SCAN=127.0.0.1
ENV RESULTS_BUCKET=${results_bucket_arn}

ENTRYPOINT [ "sh", "task_script.sh", "-A", "-v" ]